sudo: false

services:
  - docker

language: java

env:
  global:
    - secure: "SybOpZqAOPxbI9YQKlnF/1OJ9spKeN1q2M2Z/oiBPogWdZvkvgsn9gZAVTmWnC6Zn00i/76fXUOFDEOuqDYJmUzUb+0TMmCRDh6YxiP9+ED5ds/3VOmf4nLWwrMlQqATFU73DzxHVDQRqNvXgwac4nGG0TEjH79pdC4MfbpWXCxTcR8k3gABaKiXyXURZtJpQAf7aEMCAMGez6XiU4nqqvLc48wuTIlb03hqr6Mr+6EV7JtXPSjjCkL3tSL3dkkQ5VU+3R7+gU1MtboScJncWDK/cEM3yUJy/m8a0jEadOt+nqE81ysBA4Hu8OZf+rjZvQAlp05IDPJ1SxfANrQSBLaNNFsS8Y0aRaQDUmJaGTrKwZfcbezdWbVb2g8/Juy2aqTKxSuXBV3EOWx6mTvLSgIbA2LB6jVJ58DKL+JzFjffyVh8/ZUFHpeiKYWs9RI+cxEJK/qGe7MdnOds1ZbwjXPRQ1eGAo6v3YwRWHxYGMxczloqpFkJGSUU0hpcArQ8NK6j4ohRVvsA+QrHVxKYE7K4iBGHJfC3zq9RIwFGg7l66NI2bouY5UuohXAoYkFLDJT1YfiBwVh0H1qGJBNQ4QlkgpMzyL713DCRO/3FvsVqYz2xw419Id+Zp+NmNSQDdvVb2T8AVSLfVVLlcp7qfrLlEZQpBfQmX26ohtsCrO4="

addons:
    apt:
        packages:
            - sshpass

cache:
  directories:
  - $HOME/.m2

install: true
script:
  - mvn install #-DskipTests=true -Dmaven.javadoc.skip=true -B -V
#  - chmod +x bin/build.sh
#  - bin/build.sh

after_success:
  - |
       $(npm bin)/set-up-ssh --key "$encrypted_XXXXXXXXXXXX_key" \
                             --iv "$encrypted_XXXXXXXXXXXX_iv" \
                             --path-encrypted-key ".travis/github_deploy_key.enc"
  - export SSHPASS=$DEPLOY_PASSWORD
  - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/scripts/deploy.sh

#before_deploy:
#  - openssl aes-256-cbc -K $encrypted_821806d8f5e1_key -iv $encrypted_821806d8f5e1_iv -in .travis/github_deploy_key.enc -out github_deploy_key -d
#  - eval "$(ssh-agent -s)"

#deploy:
#  - provider: script
#    script: bash scripts/deploy.sh staging
#    on:
#      branch: develop
#  - provider: script
#    script: bash scripts/deploy.sh production
#    on:
#      branch: master