sudo: false

services:
  - docker

language: java

env:
  global:
    - secure: "EOqB3gkNStmsMEkog3RXRhvyiMiDd65fpk0e88TMrKDyd+Pe5gKkeSq6eEiqbJU0muA/N65ob/JRjmI/dZRFQK7NIALRBpz9VgDEYyuUFCyfvThSJ+8fcc0JSicWrF48jdPRUDZB9T5fXpPYNyhNA+gl3JyCCbWa2b125mJahIa1UkdYGnm8dCciXJ4lWIdGR1R+nz1SYD5QHAtCRxRW1amM3H3VVR8LIrWCrGGK6VPdsguxd/5kAHbOSLWHcmLFcLUTRGg5FlFOereealjWVp01FKLtR4XQnd8I5CrR3RBEAIEyjNOBFEtPK5aIK0PZGxHe5eQuA1GBcN4+VLbP8KpE7c+jCZnb/6KFrbRzKYbCJAQZ1uOtIZqhVqoxs4jkl8g4YZfRIpVZaSLCr5eVsfdU35uslZEaiv6aoQjtMzGwXuBmqISCOW603KhG3TQJWzqrRsS0kXMPap2l8VgRxu/qilvAf0qltGfFRWAteqjyW75/AFzy/A92z7sVge4Rw8x4+7sSKpOuGU1XP3YHNYnUtIZW6h5RO04jBHOa+d0e6ZFPWQVv/iPC+kPH88YSsvq3JyjuaXry8uPguPI6Mgs6R848dfY5oj9s3XtAn/eqx7DggKKO0Wso9tST6iRtv6AsPppyEvUX1IOmvWVfHx1HsLlwtwXdS/pR6dUPBBg="

cache:
  directories:
  - $HOME/.m2

before_install:
  - openssl aes-256-cbc -K $encrypted_821806d8f5e1_key -iv $encrypted_821806d8f5e1_iv -in github_deploy_key.enc -out github_deploy_key -d

#install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

install: true
script:
  - ./mvnw clean install
  - bin/build.sh

after_success:
  - |
       $(npm bin)/set-up-ssh --key "$encrypted_XXXXXXXXXXXX_key" \
                             --iv "$encrypted_XXXXXXXXXXXX_iv" \
                             --path-encrypted-key ".travis/github_deploy_key.enc"

deploy:
#  - provider: script
#    script: bash scripts/deploy.sh staging
#    on:
#      branch: develop
  - provider: script
    script: bash scripts/deploy.sh production
    on:
      branch: master